---
version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      # - run:            
      #    command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
      #    shell: powershell.exe
      # - run:
      #    command: echo hello && echo world
      #    shell: bash.exe
      - run:
         command: echo hello & echo world
         shell: cmd.exe
      - run:
         command:  choco install strawberryperl
         shell: cmd.exe
      - run:
         command: dir c:\strawberry\perl\bin\
         shell: cmd.exe     
      - run:
         command: ls -l /c/strawberry/perl/bin/
         shell: bash.exe  
# Cheat to install dependencies, install last release.
      - run:
         command: cd /tmp; /c/strawberry/perl/bin/cpanm Moose
         shell: bash.exe   
      - run:
         command: c:\strawberry\perl\bin\perl -v
         shell: cmd.exe
      - run:
         command: /c/strawberry/perl/bin/prove -l t/*.t
         shell: bash.exe
      # - run:
      #    command: c:\strawberry\perl\bin\prove.bat -l t/*.t
      #    shell: cmd.exe   
         